import { COMPLAINT_LABELS, L4_STEPS, primaryProposal, reportFileName, reportToXml, ROLE_LABELS, RULES, STATUS_LABELS, type Case, type Report, type ReportCell, type ReportTable, type RootCauseBriefing } from '@reclaim/shared'
import { formatDate, formatDateTime } from '@/lib/format'

/**
 * Writes the shared report model to Excel, PDF and XML in the browser. exceljs and jspdf are loaded
 * on the first export only, so they stay out of the main bundle.
 */
export type ExportFormat = 'xlsx' | 'pdf' | 'xml'

const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/
const PRINCIPLE = 'The model reads and explains. Code decides about money. A person approves every SAP change.'

export function downloadBlob(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function period(r: Report) {
  return r.meta.from || r.meta.to ? `${r.meta.from ?? 'start'} to ${r.meta.to ?? 'today'}` : 'All cases'
}

const metaRows = (r: Report): [string, string][] => [
  ['Generated', formatDateTime(r.meta.generatedAt) + ' UTC'],
  ['Generated by', r.meta.generatedBy],
  ['SAP system', r.meta.sapMode],
  ['Period', period(r)],
  ['Cases', String(r.meta.caseCount)],
]

export async function reportBlob(r: Report, format: ExportFormat): Promise<Blob> {
  if (format === 'xml') return new Blob([reportToXml(r)], { type: 'application/xml' })
  return format === 'xlsx' ? toXlsx(r) : toPdf(r)
}

export async function exportReport(r: Report, format: ExportFormat, suffix = '') {
  downloadBlob(await reportBlob(r, format), `${reportFileName(r, suffix)}.${format}`)
}

async function toXlsx(r: Report): Promise<Blob> {
  const { default: ExcelJS } = await import('exceljs')
  const wb = new ExcelJS.Workbook()
  wb.creator = r.meta.generatedBy
  wb.created = new Date(r.meta.generatedAt)
  wb.title = r.meta.title

  for (const t of r.tables) {
    const ws = wb.addWorksheet(t.title)
    let headerRow = 1
    if (t.key === 'summary') {
      ws.addRow([r.meta.title]).font = { bold: true, size: 14 }
      for (const m of metaRows(r)) ws.addRow(m)
      ws.addRow([PRINCIPLE]).font = { italic: true, color: { argb: 'FF6B7280' } }
      ws.addRow([])
      headerRow = ws.rowCount + 1
    }
    ws.columns = t.columns.map((c) => ({ key: c.key, width: Math.max(c.width ?? 12, c.label.length + 2) }))
    const head = ws.getRow(headerRow)
    head.values = t.columns.map((c) => c.label)
    head.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    head.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F766E' } }
    })
    for (const row of t.rows) {
      const added = ws.addRow(t.columns.map((c) => xlsxValue(row[c.key] ?? null)))
      t.columns.forEach((c, i) => {
        const cell = added.getCell(i + 1)
        if (c.money && typeof cell.value === 'number') cell.numFmt = '#,##0.00'
        if (cell.value instanceof Date) cell.numFmt = 'yyyy-mm-dd hh:mm:ss'
      })
    }
    ws.views = [{ state: 'frozen', ySplit: headerRow }]
    if (t.rows.length) ws.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow + t.rows.length, column: t.columns.length } }
  }
  const buf = await wb.xlsx.writeBuffer()
  return new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

function xlsxValue(v: ReportCell): string | number | boolean | Date | null {
  if (typeof v === 'string' && ISO.test(v)) return new Date(v)
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  return v
}

/** The standard PDF fonts only cover Latin-1; replace what they cannot draw. */
const pdfText = (s: string) =>
  s
    .replace(/→/g, '->')
    .replace(/←/g, '<-')
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/…/g, '...')
    .replace(/[^\t\n\r -ÿ]/g, '?')

const clip = (s: string, n: number) => (s.length > n ? s.slice(0, n - 3) + '...' : s)

/** One value on one line: objects as key=value pairs, lists of records as a count. */
function flat(v: unknown): string {
  if (v === null || typeof v !== 'object') return String(v)
  if (Array.isArray(v)) return v.every((x) => x === null || typeof x !== 'object') ? v.join(', ') || 'none' : `${v.length} item${v.length === 1 ? '' : 's'}`
  const pairs = Object.entries(v as Record<string, unknown>).filter(([, x]) => x !== null && x !== '' && (typeof x !== 'object' || (Array.isArray(x) && x.length === 0)))
  return pairs.map(([k, x]) => `${k}=${Array.isArray(x) ? 'none' : String(x)}`).join(', ') || '{}'
}

const hhmmss = (iso: string) => new Date(iso).toISOString().slice(11, 19)

/** Event detail as "key: value" lines instead of raw JSON, a few lines at most. */
export function readableDetail(json: string, maxLines = 6): string {
  let obj: unknown
  try {
    obj = JSON.parse(json)
  } catch {
    return clip(json, 300)
  }
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return clip(json, 300)
  const lines = Object.entries(obj as Record<string, unknown>)
    .filter(([, v]) => v !== null && v !== undefined && v !== '')
    .map(([k, v]) => `${k}: ${clip(flat(v), 90)}`)
  return lines.length > maxLines ? [...lines.slice(0, maxLines), `+ ${lines.length - maxLines} more`].join('\n') : lines.join('\n')
}

function pdfCell(v: ReportCell, key: string, money?: boolean): string {
  if (v === null) return ''
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  if (typeof v === 'number') return money ? v.toFixed(2) : String(v)
  if (ISO.test(v)) return key === 'at' ? `${formatDateTime(v).slice(0, 11)} ${hhmmss(v)}` : formatDateTime(v)
  if (key === 'detail') return pdfText(readableDetail(v))
  return pdfText(clip(v, 220))
}

type Doc = InstanceType<typeof import('jspdf').jsPDF>
type AutoTable = typeof import('jspdf-autotable').autoTable

const TEAL: [number, number, number] = [15, 118, 110]
const MUTED: [number, number, number] = [107, 114, 128]
const ZEBRA: [number, number, number] = [244, 246, 248]

async function pdfLibs(orientation: 'portrait' | 'landscape') {
  const [{ jsPDF }, { autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')])
  return { doc: new jsPDF({ orientation, unit: 'pt', format: 'a4' }), autoTable }
}

const lastY = (doc: Doc) => (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY

/** Section heading with a rule under it; starts a new page when there is no room for a heading and a few rows. */
function heading(doc: Doc, title: string, y: number, margin: number): number {
  const h = doc.internal.pageSize.getHeight()
  if (y > h - 110) {
    doc.addPage()
    y = 50
  }
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(...TEAL).text(pdfText(title), margin, y)
  doc.setDrawColor(...TEAL).setLineWidth(0.8).line(margin, y + 4, doc.internal.pageSize.getWidth() - margin, y + 4)
  doc.setTextColor(0, 0, 0)
  return y + 12
}

function footer(doc: Doc, left: string, margin: number) {
  const pages = doc.getNumberOfPages()
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal').setFontSize(7.5).setTextColor(...MUTED)
    doc.text(pdfText(left), margin, h - 20)
    doc.text(`Page ${i} of ${pages}`, w - margin, h - 20, { align: 'right' })
  }
}

/** A report table with widths from the column definitions, so no column is squeezed to one letter. */
function drawTable(doc: Doc, autoTable: AutoTable, t: ReportTable, startY: number, margin: number) {
  const avail = doc.internal.pageSize.getWidth() - margin * 2
  const total = t.columns.reduce((s, c) => s + (c.width ?? 12), 0)
  autoTable(doc, {
    startY,
    margin: { left: margin, right: margin, top: 50, bottom: 40 },
    head: [t.columns.map((c) => c.label)],
    body: t.rows.length ? t.rows.map((row) => t.columns.map((c) => pdfCell(row[c.key] ?? null, c.key, c.money))) : [[{ content: 'None in this period', colSpan: t.columns.length, styles: { textColor: MUTED, fontStyle: 'italic' } }]],
    styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: TEAL, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: ZEBRA },
    columnStyles: Object.fromEntries(
      t.columns.map((c, i) => [i, { cellWidth: (avail * (c.width ?? 12)) / total, halign: c.money || c.key === 'quantity' || c.key === 'durationMs' ? 'right' : 'left' }]),
    ),
  })
  return lastY(doc)
}

async function toPdf(r: Report): Promise<Blob> {
  const { doc, autoTable } = await pdfLibs('landscape')
  const margin = 36
  doc.setFillColor(...TEAL).rect(0, 0, doc.internal.pageSize.getWidth(), 6, 'F')
  doc.setFont('helvetica', 'bold').setFontSize(16).text(pdfText(r.meta.title), margin, 44)
  doc.setFont('helvetica', 'italic').setFontSize(9).setTextColor(...MUTED).text(PRINCIPLE, margin, 60)
  doc.setTextColor(0, 0, 0)
  autoTable(doc, { startY: 72, theme: 'plain', margin: { left: margin }, tableWidth: 300, styles: { fontSize: 9, cellPadding: 2 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 90 } }, body: metaRows(r).map(([k, v]) => [k, pdfText(v)]) })

  let y = lastY(doc) + 22
  for (const t of r.tables) {
    if (t.key === 'summary') {
      y = heading(doc, 'Summary', y, margin)
      autoTable(doc, { startY: y, margin: { left: margin, bottom: 40 }, tableWidth: 420, styles: { fontSize: 8, cellPadding: 3 }, headStyles: { fillColor: TEAL }, alternateRowStyles: { fillColor: ZEBRA }, columnStyles: { 1: { halign: 'right' } }, head: [['Metric', 'Value']], body: t.rows.map((row) => [pdfText(String(row.metric)), row.value == null ? '-' : String(row.metric).includes(`(${r.meta.currency})`) ? Number(row.value).toFixed(2) : String(row.value)]) })
      y = lastY(doc) + 24
      continue
    }
    y = heading(doc, `${t.title} (${t.rows.length})`, y, margin)
    y = drawTable(doc, autoTable, t, y, margin) + 24
  }
  footer(doc, `Reclaim audit report · ${period(r)} · generated ${formatDateTime(r.meta.generatedAt)} UTC`, margin)
  return doc.output('blob')
}

export interface CasePackOptions {
  generatedBy: string
  sapMode?: string
  now?: Date
}

/** One case as a printable audit pack: what the customer asked, what code decided, who approved, what SAP got, and every step. */
export async function caseAuditPdf(c: Case, opts: CasePackOptions): Promise<Blob> {
  const { doc, autoTable } = await pdfLibs('portrait')
  const margin = 40
  const w = doc.internal.pageSize.getWidth()
  const avail = w - margin * 2
  const now = opts.now ?? new Date()
  const p = primaryProposal(c)
  const d = p?.decision

  doc.setFillColor(...TEAL).rect(0, 0, w, 74, 'F')
  doc.setTextColor(255, 255, 255).setFont('helvetica', 'bold').setFontSize(18).text('Audit pack', margin, 34)
  doc.setFont('helvetica', 'normal').setFontSize(11).text(pdfText(`${c.id} · ${STATUS_LABELS[c.status]}`), margin, 54)
  doc.setFontSize(8).text(pdfText(`Generated ${formatDateTime(now.toISOString())} UTC by ${opts.generatedBy}`), w - margin, 34, { align: 'right' })
  doc.text(`SAP system: ${opts.sapMode ?? 'DS4'}`, w - margin, 48, { align: 'right' })
  doc.setTextColor(0, 0, 0).setFont('helvetica', 'bold').setFontSize(12)
  const subject = doc.splitTextToSize(pdfText(c.subject), avail) as string[]
  doc.text(subject, margin, 98)
  doc.setFont('helvetica', 'italic').setFontSize(8).setTextColor(...MUTED).text(PRINCIPLE, margin, 98 + subject.length * 14)
  doc.setTextColor(0, 0, 0)

  const kv = (rows: [string, string | null | undefined][], startY: number) => {
    const body = rows.filter((r): r is [string, string] => !!r[1]).map(([k, v]) => [k, pdfText(v)])
    autoTable(doc, { startY, theme: 'plain', margin: { left: margin, right: margin, bottom: 40 }, styles: { fontSize: 9, cellPadding: { top: 2, bottom: 2, left: 0, right: 4 } }, columnStyles: { 0: { cellWidth: 120, textColor: MUTED }, 1: { fontStyle: 'bold' } }, body })
    return lastY(doc)
  }
  const table = (head: string[], body: string[][], widths: number[], startY: number, empty: string) => {
    const total = widths.reduce((a, b) => a + b, 0)
    autoTable(doc, {
      startY,
      margin: { left: margin, right: margin, top: 50, bottom: 40 },
      head: [head],
      body: body.length ? body.map((r) => r.map(pdfText)) : [[{ content: empty, colSpan: head.length, styles: { textColor: MUTED, fontStyle: 'italic' } }]],
      styles: { fontSize: 8, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
      headStyles: { fillColor: TEAL, textColor: 255 },
      alternateRowStyles: { fillColor: ZEBRA },
      columnStyles: Object.fromEntries(widths.map((x, i) => [i, { cellWidth: (avail * x) / total }])),
    })
    return lastY(doc)
  }
  const paragraph = (label: string, text: string, startY: number) => {
    if (!text.trim()) return startY
    doc.setFont('helvetica', 'bold').setFontSize(9).text(label, margin, startY + 12)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(pdfText(text.trim()), avail) as string[]
    let y = startY + 26
    for (const line of lines) {
      if (y > doc.internal.pageSize.getHeight() - 50) {
        doc.addPage()
        y = 50
      }
      doc.text(line, margin, y)
      y += 12
    }
    return y
  }

  let y = heading(doc, 'Complaint', 98 + subject.length * 14 + 22, margin)
  y = kv(
    [
      ['Received', formatDateTime(c.receivedAt) + ' UTC'],
      ['From', c.from],
      ['Customer', [c.customer, c.customerName].filter(Boolean).join(' · ')],
      ['Invoice', c.invoiceNumber],
      ['Complaint', COMPLAINT_LABELS[c.complaintType]],
      ['Claimed', c.facts?.claimedQuantity != null ? `${c.facts.claimedQuantity} ${c.facts.unit ?? ''}`.trim() : null],
      ['Processing', c.aiMode === 'rules_only' ? 'Rules only' : 'AI assisted'],
      ['Anomalies', c.anomalies.join('; ') || null],
    ],
    y,
  )

  y = heading(doc, 'Decision (made by code, not by the model)', y + 22, margin)
  if (!d || !p) {
    doc.setFont('helvetica', 'italic').setFontSize(9).setTextColor(...MUTED).text('No proposal yet.', margin, y + 10)
    doc.setTextColor(0, 0, 0)
    y += 16
  } else {
    y = kv(
      [
        ['Rule', `${d.ruleId} · ${RULES[d.ruleId].situation}`],
        ['Document', d.documentType === 'NONE' ? 'No SAP document' : `${d.documentType}${d.reasonCode ? ` · reason ${d.reasonCode}` : ''}`],
        ['Quantity', d.quantity ? `${d.quantity} ${d.unit ?? ''}`.trim() : null],
        ['Amount', `${d.amount.toFixed(2)} ${d.currency}`],
        ['Approver', d.approverRole ? ROLE_LABELS[d.approverRole] : 'No approval needed'],
        ['Intercompany', d.intercompany ? 'Yes, flagged for finance' : null],
        ['Customer confirmation', d.requiresCustomerConfirmation ? 'Required before any credit' : null],
        ['Notes', d.notes || null],
        ['Other option', c.proposals.length > 1 ? c.proposals.filter((x) => x.id !== p.id).map((x) => `${x.decision.ruleId} · ${x.decision.documentType} · ${x.decision.amount.toFixed(2)} ${x.decision.currency}`).join('; ') : null],
      ],
      y,
    )
    y = paragraph('Explanation', p.explanation, y + 4)
    if (p.policyCitations.length) y = paragraph('Policy', p.policyCitations.map((x) => `${x.ruleId}: ${x.text}`).join('\n'), y)
  }

  y = heading(doc, `Approvals (${c.approvals.length})`, y + 22, margin)
  y = table(
    ['Decided', 'Approver', 'Role', 'Decision', 'Edited qty', 'Comment'],
    c.approvals.map((a) => [formatDateTime(a.decidedAt), a.actor, ROLE_LABELS[a.role], a.decision, a.editedQuantity == null ? '' : String(a.editedQuantity), a.comment]),
    [16, 14, 16, 11, 9, 34],
    y,
    'Not decided yet.',
  )

  y = heading(doc, `SAP documents (${c.sapDocuments.length})`, y + 22, margin)
  y = table(
    ['Created', 'Type', 'Number', 'Released', 'Gateway approval record'],
    c.sapDocuments.map((s) => [formatDateTime(s.createdAt), s.type, s.number, s.released ? 'yes' : 'no', s.gatewayLogId ?? '']),
    [18, 8, 14, 10, 50],
    y,
    'Nothing written to SAP.',
  )

  const events = [...c.events].sort((a, b) => a.at.localeCompare(b.at))
  // The date once per day, then times with seconds: the agent's steps are seconds apart.
  const when = (iso: string, i: number) => (i === 0 || iso.slice(0, 10) !== events[i - 1]!.at.slice(0, 10) ? `${formatDateTime(iso).slice(0, 11)}\n${hhmmss(iso)}` : hhmmss(iso))
  y = heading(doc, `Audit trail (${events.length} events)`, y + 22, margin)
  table(
    ['Time', 'Process step', 'Event', 'Detail', 'ms'],
    events.map((e, i) => [
      when(e.at, i),
      e.l4Step ? `${e.l4Step} ${L4_STEPS[e.l4Step].name}` : e.kind,
      e.title,
      Object.keys(e.detail).length ? readableDetail(JSON.stringify(e.detail), 4) : '',
      e.durationMs == null ? '' : String(e.durationMs),
    ]),
    [11, 21, 27, 35, 6],
    y,
    'No events.',
  )

  footer(doc, `Reclaim · audit pack ${c.id} · invoice ${c.invoiceNumber ?? 'unknown'}`, margin)
  return doc.output('blob')
}

export async function exportCaseAuditPack(c: Case, opts: CasePackOptions) {
  downloadBlob(await caseAuditPdf(c, opts), `reclaim-audit-pack-${c.id}.pdf`)
}

const TREND_WORDS = { rising: 'getting worse', stable: 'steady', falling: 'easing' } as const
const amount = (v: number, cur: string) => `${v.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${cur}`

/** Root causes as a report a manager can forward: the headline, then per problem what it costs, why, and who fixes it. */
export async function rootCausesPdf(b: RootCauseBriefing): Promise<Blob> {
  const { doc, autoTable } = await pdfLibs('portrait')
  const margin = 40
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()
  const avail = w - margin * 2
  const cur = b.totals.currency
  const n = b.clusters.length

  doc.setFillColor(...TEAL).rect(0, 0, w, 74, 'F')
  doc.setTextColor(255, 255, 255).setFont('helvetica', 'bold').setFontSize(18).text('Root causes report', margin, 34)
  doc.setFont('helvetica', 'normal').setFontSize(11).text(pdfText(`Complaints from ${formatDate(b.period.from)} to ${formatDate(b.period.to)}`), margin, 54)
  doc.setFontSize(8).text(pdfText(`Generated ${formatDateTime(b.generatedAt)} UTC`), w - margin, 34, { align: 'right' })

  let y = 104
  const lines = (text: string, size: number, style: 'normal' | 'bold' | 'italic', gap = size + 3, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFont('helvetica', style).setFontSize(size).setTextColor(...color)
    for (const line of doc.splitTextToSize(pdfText(text), avail) as string[]) {
      if (y > h - 50) {
        doc.addPage()
        y = 50
      }
      doc.text(line, margin, y)
      y += gap
    }
    doc.setTextColor(0, 0, 0)
  }

  const share = b.totals.value ? Math.round((b.totals.clusteredValue / b.totals.value) * 100) : 0
  lines(n ? `${n} ${n === 1 ? 'problem' : 'problems'} caused ${amount(b.totals.clusteredValue, cur)} of credit notes, ${share}% of all credit given.` : 'No problem came back three times or more.', 14, 'bold', 18)
  const worded = b.clusters.some((c) => c.wordedBy === 'model') ? `the wording is by ${b.generatedBy} and is checked to contain no number that is not in the data` : 'the wording is standard text'
  lines(`From ${b.totals.complaints} complaints. Every figure is computed from the data; ${worded}.`, 9, 'italic', 12, MUTED)
  if (b.note) lines(b.note, 9, 'italic', 12, MUTED)

  b.clusters.forEach((c, i) => {
    y = heading(doc, `${i + 1}. ${c.title}`, y + 18, margin) + 4
    lines(`${amount(c.value, c.currency)} · ${c.complaints} complaints · ${c.deskHours} h desk time · ${TREND_WORDS[c.trend]} (${c.last30Days} in the last 30 days)${c.openCaseIds.length ? ` · open now: ${c.openCaseIds.join(', ')}` : ''}`, 9, 'bold', 12)
    y += 2
    lines(`Why: ${c.rootCause}`, 9, 'normal', 12)
    lines(`What to do (${c.owner}): ${c.action}`, 9, 'normal', 12)
  })

  if (n) {
    y = heading(doc, 'Summary', y + 18, margin)
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin, bottom: 40 },
      head: [['Problem', 'Complaints', 'Credit', 'Trend', 'Who fixes it']],
      body: b.clusters.map((c) => [pdfText(c.title), String(c.complaints), amount(c.value, c.currency), TREND_WORDS[c.trend], pdfText(c.owner)]),
      styles: { fontSize: 8, cellPadding: 4 },
      headStyles: { fillColor: TEAL, textColor: 255 },
      alternateRowStyles: { fillColor: ZEBRA },
      columnStyles: { 0: { cellWidth: avail * 0.36 }, 1: { halign: 'right' }, 2: { halign: 'right' } },
    })
  }

  footer(doc, `Reclaim · root causes · ${b.totals.live} complaints from this desk, ${b.totals.archive} from the archive (sample data)`, margin)
  return doc.output('blob')
}

export async function exportRootCauses(b: RootCauseBriefing) {
  downloadBlob(await rootCausesPdf(b), `reclaim-root-causes-${b.generatedAt.slice(0, 10)}.pdf`)
}
