import { reportFileName, reportToXml, type Report, type ReportCell, type ReportTable } from '@reclaim/shared'
import { formatDateTime } from '@/lib/format'

/**
 * Writes the shared report model to Excel, PDF and XML in the browser. exceljs and jspdf are loaded
 * on the first export only, so they stay out of the main bundle.
 */
export type ExportFormat = 'xlsx' | 'pdf' | 'xml'

const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/
const PRINCIPLE = 'The model reads and explains. Code decides about money. A person approves every SAP change.'

export function downloadBlob(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function period(r: Report) {
  return r.meta.from || r.meta.to ? `${r.meta.from ?? 'start'} to ${r.meta.to ?? 'today'}` : 'All cases'
}

const metaRows = (r: Report): [string, string][] => [
  ['Generated', formatDateTime(r.meta.generatedAt) + ' UTC'],
  ['Generated by', r.meta.generatedBy],
  ['SAP mode', r.meta.sapMode],
  ['Period', period(r)],
  ['Cases', String(r.meta.caseCount)],
]

export async function reportBlob(r: Report, format: ExportFormat): Promise<Blob> {
  if (format === 'xml') return new Blob([reportToXml(r)], { type: 'application/xml' })
  return format === 'xlsx' ? toXlsx(r) : toPdf(r)
}

export async function exportReport(r: Report, format: ExportFormat, suffix = '') {
  downloadBlob(await reportBlob(r, format), `${reportFileName(r, suffix)}.${format}`)
}

async function toXlsx(r: Report): Promise<Blob> {
  const { default: ExcelJS } = await import('exceljs')
  const wb = new ExcelJS.Workbook()
  wb.creator = r.meta.generatedBy
  wb.created = new Date(r.meta.generatedAt)
  wb.title = r.meta.title

  for (const t of r.tables) {
    const ws = wb.addWorksheet(t.title)
    let headerRow = 1
    if (t.key === 'summary') {
      ws.addRow([r.meta.title]).font = { bold: true, size: 14 }
      for (const m of metaRows(r)) ws.addRow(m)
      ws.addRow([PRINCIPLE]).font = { italic: true, color: { argb: 'FF6B7280' } }
      ws.addRow([])
      headerRow = ws.rowCount + 1
    }
    ws.columns = t.columns.map((c) => ({ key: c.key, width: Math.max(c.width ?? 12, c.label.length + 2) }))
    const head = ws.getRow(headerRow)
    head.values = t.columns.map((c) => c.label)
    head.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    head.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F766E' } }
    })
    for (const row of t.rows) {
      const added = ws.addRow(t.columns.map((c) => xlsxValue(row[c.key] ?? null)))
      t.columns.forEach((c, i) => {
        const cell = added.getCell(i + 1)
        if (c.money && typeof cell.value === 'number') cell.numFmt = '#,##0.00'
        if (cell.value instanceof Date) cell.numFmt = 'yyyy-mm-dd hh:mm:ss'
      })
    }
    ws.views = [{ state: 'frozen', ySplit: headerRow }]
    if (t.rows.length) ws.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow + t.rows.length, column: t.columns.length } }
  }
  const buf = await wb.xlsx.writeBuffer()
  return new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

function xlsxValue(v: ReportCell): string | number | boolean | Date | null {
  if (typeof v === 'string' && ISO.test(v)) return new Date(v)
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  return v
}

/** The standard PDF fonts only cover Latin-1; replace what they cannot draw. */
const pdfText = (s: string) =>
  s
    .replace(/→/g, '->')
    .replace(/←/g, '<-')
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/…/g, '...')
    .replace(/[^\t\n\r -ÿ]/g, '?')

function pdfCell(v: ReportCell, money?: boolean): string {
  if (v === null) return ''
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  if (typeof v === 'number') return money ? v.toFixed(2) : String(v)
  if (ISO.test(v)) return formatDateTime(v)
  return pdfText(v.length > 220 ? v.slice(0, 217) + '...' : v)
}

async function toPdf(r: Report): Promise<Blob> {
  const [{ jsPDF }, { autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')])
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })
  const width = doc.internal.pageSize.getWidth()
  const margin = 36
  const teal: [number, number, number] = [15, 118, 110]

  doc.setFont('helvetica', 'bold').setFontSize(16).text(pdfText(r.meta.title), margin, 48)
  doc.setFont('helvetica', 'italic').setFontSize(9).setTextColor(107, 114, 128).text(PRINCIPLE, margin, 64)
  doc.setTextColor(0, 0, 0)
  autoTable(doc, { startY: 76, theme: 'plain', margin: { left: margin }, tableWidth: 320, styles: { fontSize: 9, cellPadding: 2 }, columnStyles: { 0: { fontStyle: 'bold' } }, body: metaRows(r).map(([k, v]) => [k, pdfText(v)]) })

  const draw = (t: ReportTable, startY: number) => {
    doc.setFont('helvetica', 'bold').setFontSize(12).text(`${t.title} (${t.rows.length})`, margin, startY)
    autoTable(doc, {
      startY: startY + 6,
      margin: { left: margin, right: margin, top: 40 },
      head: [t.columns.map((c) => c.label)],
      body: t.rows.length ? t.rows.map((row) => t.columns.map((c) => pdfCell(row[c.key] ?? null, c.money))) : [[{ content: 'None in this period', colSpan: t.columns.length }]],
      styles: { fontSize: t.columns.length > 10 ? 6.5 : 7.5, cellPadding: 2.5, overflow: 'linebreak' },
      headStyles: { fillColor: teal, textColor: 255 },
      alternateRowStyles: { fillColor: [244, 246, 248] },
      columnStyles: Object.fromEntries(t.columns.map((c, i) => [i, { halign: c.money || c.key === 'quantity' || c.key === 'durationMs' ? 'right' : 'left' }])),
    })
  }

  const last = () => (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY
  const [summary, ...rest] = r.tables
  if (summary) draw(summary, last() + 24)
  for (const t of rest) {
    doc.addPage()
    draw(t, 48)
  }

  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(107, 114, 128)
    doc.text(`Reclaim audit report · ${period(r)} · generated ${formatDateTime(r.meta.generatedAt)} UTC`, margin, doc.internal.pageSize.getHeight() - 18)
    doc.text(`Page ${i} of ${pages}`, width - margin, doc.internal.pageSize.getHeight() - 18, { align: 'right' })
  }
  return doc.output('blob')
}
